### ISSUE TITLE
cvpr16_gmad/database/toolbix.tar.gz was not found on this server

### ISSUE THREAD

**Issue by tobechao** [xialeiliu/RankIQA#1]
HI，thank you for your RankIQA, I want to be an experiment, but when i download data of  Waterloo,there is a error, toolbix.tar.gz was not found on this server. Excuse me, can you send me a copy of toolbix.tar.gz? thank you very much!

**Comment by xialeiliu** [comment]
Hi, thanks for your interest, I have tried to download the toolbox you needed, which was available online. Maybe you could try it once again.

**Comment by tobechao** [comment]
thank you , en, i open the link "https://ece.uwaterloo.ca/~zduanmu/cvpr16_gmad/database/toolbix.tar.gz" ,the link has been opened error, named " 
Not Found

The requested URL /~zduanmu/cvpr16_gmad/database/toolbix.tar.gz was not found on this server.", can you give me a online link? 
HI, I still have another question,Can I reproduce the essay based on the script you provided?

**Comment by xialeiliu** [comment]
Hi,
It works for me, anyway, I send it to you by email.

Someone already reproduced the similar results as reported in the paper by
using the code, therefore you should be able to do so.​
 gMADToolboxV1.0-beta3 (1).rar
<https://drive.google.com/file/d/1K4IJmJn15mTPbxSpmtWuVKspdL-_ZxoL/view?usp=drive_web>
​

**Comment by tobechao** [comment]
Thank you very much, I have downloaded it, I am going to repeat the thesis.
