### ISSUE TITLE
关于训练好的模型

### ISSUE THREAD

**Issue by shixiaoxi1** [xialeiliu/RankIQA#10]
我下载了Rank_tid2013.caffemodel以及FT_tid2013.caffemodel并在TID2013的数据集上进行了预测，但是预测的结果LCC和SROCC的分数在两个模型上分别只有0.6左右和0.4左右，这是为什么呢，这个模型不是训练好的模型么

**Comment by xialeiliu** [comment]
Rank模型测试的结果在0.6左右是正常，和文中的结果是一致的， FT模型测试的结果应该是错的，一般应该在0.8左右。你可以检查下是不是deploy文件的问题，因为两个模型测试的deploy不一样。

**Comment by shixiaoxi1** [comment]
感谢回答，的确是因为deploy文件的问题，用了FT的deploy文件后得分都在0.8左右了。
还有一个问题想请教，如果我想测试自己的图片的话，在代码中循环每张图片后得到的平均得分（pre[i]）就是该图片的绝对IQA分数么？数值越大代表质量越高么？如果是的话这个分数的范围是多少呢，谢谢！

**Comment by xialeiliu** [comment]
TID2013数据库的范围在0－7之间，越大越好；
LIVE数据库的范围在0－100之间，越小越好。

**Comment by shixiaoxi1** [comment]
谢谢回答！
