### ISSUE TITLE
about the pair images ? 

### ISSUE THREAD

**Issue by ranjiewwen** [xialeiliu/RankIQA#12]
- i konw we can get lots of distorted image from refrence image . and different distorted level , can distinguish the rank quality.

- so the pair image only from the same image and different degree of distortion  ? and can't from different image? 
- I don't know whether my understanding is right  ? can you help me , thanks

**Comment by xialeiliu** [comment]
Actually both cases you mentioned work well in our experience. But in the paper we always sample the paired images from the same image.

**Comment by ranjiewwen** [comment]
thanks ,  but when the from different image ,  how we distinguish which one quality is better, and only base the distorted level?

**Comment by xialeiliu** [comment]
Yeah, in the first phase of training (refer to RankIQA), the quality is only based on the distorted levels.
To answer your second answer, in the case of RankIQA, there is no GT scores from TID2013 dataset used for training, therefore it is difficult to distinguish the quality among different types of distortions, but it works pretty fine on each individual distortion. By finutuning on TID2013 (refer to RankIQA+FT), it manages to align the scores among all distortions, that's probably why it works much better in this case.
