### ISSUE TITLE
Testing the pre trained model

### ISSUE THREAD

**Issue by goelneha** [xialeiliu/RankIQA#13]
Hi,
I am trying to test the pre trained models with my own images using "FT_eval_all_live.py", but I am getting the following error
`Traceback (most recent call last):
  File "src/eval/FT_eval_all_live.py", line 50, in <module>
    x =  im.shape[0]
IndexError: tuple index out of range`
There is a ".txt" file used for testing, and can you please explain what are those scores appended to each of the test image, so that I can test it on my images ?
Any help would be appreciated !!

**Comment by xialeiliu** [comment]
The error might because the im is empty,  I guess you have some problems about the input file. You could check if the directory is correct. The scores in LIVE dataset are from 0-100, the smaller score, the better quality.

**Comment by goelneha** [comment]
Hello,

Thank you for the response.

That issue was handled. Can you please guide me how can i test my own
images using the pre-trained model FT_live.caffemodel.
I was able to evaluate the python script src/eval/FT_eval_all_live.py, but
now i am stuck what to do next.

Any leads would be appreciated.

Thanks in advance.

**Comment by xialeiliu** [comment]
To test on your own images, you need first to prepare the same format of .txt file. Then you need to modify the script src/eval/FT_eval_all_live.py to get the network's output in stead of computing LCC and SROCC, which is the final score you need.

**Comment by goelneha** [comment]
You mean I need to create my database in the LIVE2 format database? If yes,
then how can I do it?
Also please help me in modifying src/eval/FT_eval_all_live.py to get the
output.

As I am an amateur in this field and I am trying to learn more, any help
from your side would be appreciated.
Thank you!

**Comment by xialeiliu** [comment]
pre[i] is the average score for a particular image, and med[i] is the median score, because for each test image, 30 patches are sampled from the whole image.

**Comment by goelneha** [comment]
And can you please tell me if my approach is correct or not?

**Comment by xialeiliu** [comment]
Yeah, it's correct.

**Comment by goelneha** [comment]
I am getting the following error for some of the image files:

Traceback (most recent call last):

  File "src/eval/FT_eval_all_live.py", line 78, in <module>

    x_p = np.random.randint(x-224,size=1)[0]

  File "mtrand.pyx", line 993, in mtrand.RandomState.randint

ValueError: low >= high

Can you please explain?

**Comment by xialeiliu** [comment]
I guess you have problem with reading images.
