### ISSUE TITLE
How to test on custom data set ?

### ISSUE THREAD

**Issue by vismayaps** [xialeiliu/RankIQA#14]
Hi,
How do I test the pre trained model on custom dataset ? 
Thanks !!

**Comment by xialeiliu** [comment]
The output of network trained on LIVE dataset should be in the range of [0,100], the smaller, the better. Of course you could do fine-tuning on custom dataset if you have some kind of ground truth.

**Comment by vismayaps** [comment]
Can you please brief me about the steps required ? I am not able to figure
it out from the given details.

**Comment by xialeiliu** [comment]
To test on your own images, you need first to prepare the same format of .txt file. Then you need to modify the script src/eval/FT_eval_all_live.py to get the network's output in stead of computing LCC and SROCC, which is the final score you need.

**Comment by vismayaps** [comment]
I see some scores appended with the ".txt" file used by the script ? What are those scores and how can I generate the scores out of my images ?

**Comment by xialeiliu** [comment]
Those scores are from the dataset annotated by human beings, which is the ground truth to evaluate the algorithm. if you do not have the scores for you own images, you can put 0.00, in that case, you could still run the script src/eval/FT_eval_all_live.py, the pre and med in the script can be seen as the prediction, which should be in the range of [0,100], the smaller, the better.

**Comment by vismayaps** [comment]
Thank you so much !! I was able to run the test on my dataset, but its not using the GPU and its very slow, it takes 2 to 3 seconds per image. Can you help me on this ?

**Comment by xialeiliu** [comment]
It's better to recheck your devices.

**Comment by vismayaps** [comment]
I am using a Tesla K80 machine on aws.

**Comment by xialeiliu** [comment]
I have no idea with the information given by you. sorry.

**Comment by sanahtech** [comment]
I want to find quality of some images. where should I place those images?
How can I prepared .txt file for those images.
Please help me.
