### ISSUE TITLE
about the efficient backpropagation in Siamese networks?

### ISSUE THREAD

**Issue by ranjiewwen** [xialeiliu/RankIQA#15]
in paper use this words : 
![image](https://user-images.githubusercontent.com/9885492/41387480-aaae53f4-6fb9-11e8-9601-9e06ce841b30.png)

- when i rethinks this method, the siamese networks input two images as pairs , and though conv get the feature ,and feature fusion ,at last get loss. while the you use the  efficient backpropagation , batch images though the conv , and loss layer calculate all possible pairs of image loss . that is to say , the conv is only feature extract , there isn't feature fusion ,and it only has one branch of siamese networks ? so this is not a Siamese networks ? some people this can get speed up, but it maybe can't get a better result? 
- i don't konw whether i understand is correct ? can you help me ? thanks

**Comment by xialeiliu** [comment]
For our efficient back-propagation approach, we have only one branch, and input is a list of ranked images. For example, if the mini-batch is 10, we can construct 45 pairs using our approach, but in the conventional two-branch Siamese network, 10 means 5 pairs in one mini-batch, which is much less than what we can get in the end of the network.

**Comment by ranjiewwen** [comment]
这样主干网络仅仅是一个特征抽取器，只是在算loss的时候计算各个pair情况； 这样就不应该叫孪生网络了吧？？
