### ISSUE TITLE
关于训练好的模型

### ISSUE THREAD

**Issue by badaodao** [xialeiliu/RankIQA#17]
你好，我想问一下，下载下来的ft_live.caffemodel是不是rank之后，用80%的LIVE数据集训练得到的。（因为目前想做跨库测试，如果是80%的话，我可能需要自己重新用100%LIVE数据集ft一下。）

**Comment by xialeiliu** [comment]
对的

**Comment by badaodao** [comment]
Thank you!

**Comment by badaodao** [comment]
我又来了大神，我想问一下您，有没有接触过mos与dmos的转化？

**Comment by xialeiliu** [comment]
没有，谢谢您的关注。

**Comment by badaodao** [comment]
您好，我又来请教了。您的ＲａｎｋIQA真的是神作啊，每每读来都惊叹不已。这次我想问一下，您给出的ｒａｎｋ_live.caffemodel和ｒａｎｋ_tid2013.caffemodel是用８０％的ｗａｔｅｒｌｏｏ训练的，还是１００％的ｗａｔｅｒｌｏｏ训练的？因为我直接调用您的ｒａｎｋ_live.caffemodel，用live８０％微调，２０％测试出来ＳＲＯＣＣ大约是０．９６左右（好几组不同的划分），均无法达到０．９８．

**Comment by xialeiliu** [comment]
那你检查下不同iteration的结果，是不是过拟合了？

**Comment by badaodao** [comment]
哇， 谢谢你的及时回复，
（１）您漏看了一个问题，就是您的ｒａｎk_live.caffemodel用８０％的ｗａｔｅｒｌｏｏ训练的，还是１００％的ｗａｔｅｒｌｏｏ训练的？
（２）我没有做什么改变，就是用你的参数，只进行了不同组８０２０的划分，进行训练与测试的。但结果达不到０．９８．所以应该不是过拟合的问题。

**Comment by xialeiliu** [comment]
100%的Waterloo的数据, 你可以重新训练一个模型试试，现在的rank模型是我后来重新训练的，可能结果会稍有不同，你可以测试下不同循环的模型，看看最后的模型是不是最好的。

**Comment by badaodao** [comment]
恩恩了解到了！我会试试的，再次感谢您的及时回复！

**Comment by Aacrobat** [comment]
> 你好，我想问一下，下载下来的ft_live.caffemodel是不是rank之后，用80%的LIVE数据集训练得到的。（因为目前想做跨库测试，如果是80%的话，我可能需要自己重新用100%LIVE数据集ft一下。）

有没有前辈可以把使用.caffemodel 测试自己图片质量的代码开源一份呀，我不太会用训练好1模型，准确的说，我是小白

**Comment by badaodao** [comment]
大神好，我这次想问一下，您当时为何没有选用ResNet50网络？既然发现了越深越好的趋势，好像顺势可以做一下ResNet?不知道是否有尝试过？

**Comment by xialeiliu** [comment]
恩，那时候没时间试那么多网络，ResNet应该会好吧。

**Comment by badaodao** [comment]
大神，您真的不公布一下tid2013的17种失真类型制作代码吗？感觉大家（还有可怜的我）都在等你发这个，哈哈。

**Comment by Maxwell2017** [comment]
> 大神，您真的不公布一下tid2013的17种失真类型制作代码吗？感觉大家（还有可怜的我）都在等你发这个，哈哈。

请问您有复现出本论文的rank模型（tid2013数据集上的）吗？

**Comment by badaodao** [comment]
我把LIVE库的做了，但是预训练出来和作者的模型差一点点。tid没做过，虽然作者已经给了代码了。



------------------ 原始邮件 ------------------
发件人: "Maxwell2017"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 中午11:20
收件人: "xialeiliu/RankIQA"<RankIQA@noreply.github.com>;
抄送: "李梦月"<916884783@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xialeiliu/RankIQA] 关于训练好的模型 (#17)



 
大神，您真的不公布一下tid2013的17种失真类型制作代码吗？感觉大家（还有可怜的我）都在等你发这个，哈哈。
  
请问您有复现出本论文的rank模型（tid2013数据集上的）吗？

**Comment by Maxwell2017** [comment]
> 我把LIVE库的做了，但是预训练出来和作者的模型差一点点。tid没做过，虽然作者已经给了代码了。
> […](#)

我在rank模型上复现出了问题，但是在ft上是没问题的。能正常训练，但是loss降到个位数就不降了，作者的代码有哪些地方需要修改的吗？感觉我应该是哪里没有修改

**Comment by badaodao** [comment]
我不知道你的具体问题。你需要注意：预训练阶段作者自己加了关于数据和loss的.py文件。prototxt里面要调用这两个模型。所以我当时给rank_layer_live.py和netloss_live.py里面几行。我是这么加的。
import sys
sys.path.append('/opt/caffe/python')
sys.path.append('/usr/bin/python/lib/python2.7/site-packages')






------------------ 原始邮件 ------------------
发件人: "Maxwell2017"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 中午11:41
收件人: "xialeiliu/RankIQA"<RankIQA@noreply.github.com>;
抄送: "李梦月"<916884783@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xialeiliu/RankIQA] 关于训练好的模型 (#17)



 
我把LIVE库的做了，但是预训练出来和作者的模型差一点点。tid没做过，虽然作者已经给了代码了。
 …
  
我在rank模型上复现出了问题，但是在ft上是没问题的。能正常训练，但是loss降到个位数就不降了，作者的代码有哪些地方需要修改的吗？感觉我应该是哪里没有修改

**Comment by Maxwell2017** [comment]
> 我不知道你的具体问题。你需要注意：预训练阶段作者自己加了关于数据和loss的.py文件。prototxt里面要调用这两个模型。所以我当时给rank_layer_live.py和netloss_live.py里面几行。我是这么加的。 import sys sys.path.append('/opt/caffe/python') sys.path.append('/usr/bin/python/lib/python2.7/site-packages')
> […](#)

方便留个联系方式交流吗？我的微信:zhaohn1994

**Comment by badaodao** [comment]
mysunshinemoon微信
---原始邮件---
发件人:"Maxwell2017"<notifications@github.com>;
发送时间:2019年9月9日(星期一) 中午12:02
收件人:"xialeiliu/RankIQA"<RankIQA@noreply.github.com>;
抄送人:"badaodao"<916884783@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [xialeiliu/RankIQA] 关于训练好的模型 (#17)

 
我不知道你的具体问题。你需要注意：预训练阶段作者自己加了关于数据和loss的.py文件。prototxt里面要调用这两个模型。所以我当时给rank_layer_live.py和netloss_live.py里面几行。我是这么加的。 import sys sys.path.append('/opt/caffe/python') sys.path.append('/usr/bin/python/lib/python2.7/site-packages')
 …
  
方便留个联系方式交流吗？我的微信:zhaohn1994
 
&mdash;

**Comment by Maxwell2017** [comment]
> mysunshinemoon微信 ---原始邮件--- 发件人:"Maxwell2017"<notifications@github.com>; 发送时间:2019年9月9日(星期一) 中午12:02 收件人:"xialeiliu/RankIQA"<RankIQA@noreply.github.com>; 抄送人:"badaodao"<916884783@qq.com>;"Author"<author@noreply.github.com>; 主题:Re: [xialeiliu/RankIQA] 关于训练好的模型 (#17) 我不知道你的具体问题。你需要注意：预训练阶段作者自己加了关于数据和loss的.py文件。prototxt里面要调用这两个模型。所以我当时给rank_layer_live.py和netloss_live.py里面几行。我是这么加的。 import sys sys.path.append('/opt/caffe/python') sys.path.append('/usr/bin/python/lib/python2.7/site-packages') … 方便留个联系方式交流吗？我的微信:zhaohn1994 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

已申请
