### ISSUE TITLE
 the cross dataset test  problem

### ISSUE THREAD

**Issue by qianxiao111** [xialeiliu/RankIQA#18]
I trained the LIVE dataset and test TID2013. The performance of SROCC is very lower than CSIQ. I don't understand why the preformance is very lower. Especially, the scores of LIVE and TID2013 is transformed by logistic function.

**Comment by xialeiliu** [comment]
It might be because that the ground truth of two datasets are different, Larger score means worse quality in LIVE, but it's another way around in TID2013.
