### ISSUE TITLE
some question when  I run train_vgg.sh?

### ISSUE THREAD

**Issue by sunbinbin1991** [xialeiliu/RankIQA#19]
Thanks for your work.
when  I use train_vgg.sh for Live database training，no  training information in training process ? Only have the below information,
![_15380318058763](https://user-images.githubusercontent.com/15342883/46128590-8a724f00-c266-11e8-8d38-9d823455b730.png)
I thought It was wrong in my training,however, after almost 2 hours,there is training model for my training,
![_153803194922](https://user-images.githubusercontent.com/15342883/46128674-d91fe900-c266-11e8-8ccd-a6047c26b81e.png)
here is my question,
**1: Is something unusual for my training?**
**2: In above pic, what's \*solverstate stand for? is this useful?**
**3: when I uses this model (my_siamese_iter_20000.caffemodel)for test, SROCC and LCC are nagetive, sounds strange.**

**Comment by xialeiliu** [comment]
Yeah, that's strange. Usually during training, there is training information like iteration, loss.
I don't use solverstate in my experiment and the negative value  might because of your training problem.

**Comment by sunbinbin1991** [comment]
Its my fault,after rebuild my caffe,problem fix,3q anyway

**Comment by sunbinbin1991** [comment]
@xialeiliu 大佬，有微信不？

**Comment by xialeiliu** [comment]
有，你给我发邮件或者把你邮件给我
