### ISSUE TITLE
关于RankIQA的几个问题

### ISSUE THREAD

**Issue by xungeer29** [xialeiliu/RankIQA#24]
你好，关于RankIQA我还有几个问题，
1. Rank的网络为什么要用Siamese？直接进行质量等级分类不行吗？性能会下降吗？
2. 我看Rank网络的prototxt内最后一层只有一个输出，是直接输出该图像的质量等级吗？

期待您的回答，非常感谢

**Comment by xialeiliu** [comment]
1） 直接分类也可以，但是分类的信息量相比排序要小，而且分类网络测试图像质量也没有意义，具体精度我没有比较，不过这是个有意思的比较。
2）输出是质量等级，但是比较的是相对关系，不是绝对的。

**Comment by evaGao** [comment]
您好，这里的相对关系，意思是指可能输出的结果质量等级并不一定是0-5，只要两者之间有大小关系之差就可以了是吗？

**Comment by xialeiliu** [comment]
是的

**Comment by Maxwell2017** [comment]
如果这里只有大小关系，那Rank的输出应该是一个很大范围变化的数才对吧？在tid2013数据集上，他的SROCC和LCC应该很低才对吧？毕竟tid测试集的score范围都在0~9

**Comment by xialeiliu** [comment]
LCC可能会低，但是SROCC是不影响的，最终的结果是需要fine tuning的，这样尺度就没问题了
