### ISSUE TITLE
有没有TensorFlow版本

### ISSUE THREAD

**Issue by shenguquanxin** [xialeiliu/RankIQA#26]
作者您好，RankIQA真是神作！直接使用预训练模型的话，是否有TensorFlow版本的？

**Comment by xialeiliu** [comment]
那你可能需要模型转换工具吧

**Comment by shenguquanxin** [comment]
> 那你可能需要模型转换工具吧

嗯嗯，但是据说转换之后性能会有损失。您有这方面的经验吗
