### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by liujiang137** [xialeiliu/RankIQA#27]
I want to know whether there is a demo that I can evaluate the quality of my picture,thank for you answer in advance.

**Comment by xialeiliu** [comment]
Sorry for the late reply. You could just download the pretrained model and follow test part in Readme.

**Comment by wu-zhong-hua** [comment]
Thanks for the issue is open. @liujiang137 Can I have your contact information? the question I want to ask is that your problem in LW-Ricarido/Emotion-Recognize solved? Hope I can get your help，my contact is 2200680719@qq.com
