### ISSUE TITLE
请问pre_trained model是在什么平台训练出来的模型？

### ISSUE THREAD

**Issue by 110n** [xialeiliu/RankIQA#28]
**请问pre_trained model是在什么平台训练出来的模型？我用pre_trained** model在Windos上测试结果很满意，可是我想在Centos7重新微调，发现Caffe加载模型，打印的模型参数每次都不一样，也就是随机，好奇怪的现象，不知道你们有遇到吗？

**Comment by xialeiliu** [comment]
那应该是有什么弄错了，我是在Ubuntu训练的模型

**Comment by 110n** [comment]
重新训练一个模型，SROCC和LCC测试为负，但都很接近1，那说明什么？

**Comment by xialeiliu** [comment]
那说明模型训练没问题，你再检查检查为啥预测的是反的
