### ISSUE TITLE
GNC function fails

### ISSUE THREAD

**Issue by renedlog** [xialeiliu/RankIQA#32]
The GNC function fails due to YCBCR image is out of  the Valid range caused by:

`b = ycbcr + sqrt(level)*randn(sizeA);`

and fails at the next step:

`b=ycbcr2rgb(b)*255;`

```
error: ycbcr2rgb: input must be a colormap (Nx3) or RGB image (NxMx3)
error: called from
    ycbcrfunc at line 31 column 5
    ycbcr2rgb at line 51 column 7
    gnc at line 7 column 2
    tid2013_generator at line 38 column 27
    tid2013_main at line 12 column 13
```

**Comment by xialeiliu** [comment]
Have you solved it?  I couldn't replicate the error as you reported. Is it related to MATLAB version?
