### ISSUE TITLE
Issues in generating ranking data

### ISSUE THREAD

**Issue by Anguliachao** [xialeiliu/RankIQA#33]
Hi @xialeiliu ,
thanks for the nice repo. I have a few questions ,how did you generated 4 types distortion images based on Waterloo dataset, I download the dataset and try to run the code ,but it seems need you to provide the distortion method? can you give the details  or more explanation

I did see your distortion matlab code for tid2013, but the rank_live code is empty, could you give me some more clues? thanks

**Comment by xialeiliu** [comment]
You could use the toolbox of Waterloo dataset to generate 4 types distortions for LIVE dataset

**Comment by Anguliachao** [comment]
> You could use the toolbox of Waterloo dataset to generate 4 types distortions for LIVE dataset

many thanks, I solved the problem .
