### ISSUE TITLE
BM3D dictionary trouble in usage

### ISSUE THREAD

**Issue by liahung** [xialeiliu/RankIQA#36]
你好，我下载了matlab2017b（macOsX）， 运行RankIQA/data/rank_tid2013/目录下的tid2013_main.m文件，报错：
MEX-file
'~/RankIQA/data/rank_tid2013/BM3D/bm3d_thr_color.mexmaci64' 无
效:
dlopen(~/RankIQA/data/rank_tid2013/BM3D/bm3d_thr_color.mexmaci64,
6): Library not loaded: @loader_path/libmex.dylib
  Referenced from:
  ~/RankIQA/data/rank_tid2013/BM3D/bm3d_thr_color.mexmaci64
  Reason: image not found。
我检查了待处理图像的名称和路径等，确保了没有问题。于是在网上搜索希望能得到问题解决。在相关的技术论坛里看到了有问到mex错误的类似问题，说可能的原因是需要到生成mex文件的相同系统和相同版本的matlab下运行方可通过。
请问您在运行此文件时的系统和matlab版本都是什么呢？感谢！

**Comment by xialeiliu** [comment]
我用的是Ubuntu，可能是系统原因吧
