### ISSUE TITLE
采用论文中的方式生成数据，利用mobileNet_v2进行训练，loss2始终在0.4左右，pearsonr最好结果是0.46

### ISSUE THREAD

**Issue by xiaohuaibao** [xialeiliu/RankIQA#37]
因为要在移动平台进行图像质量评价，所以利用mobileNet替换了VGG的网络结构。但是训练时发现loss2降到0.4左右就不在下降了，pearsonr的最好结果也只是达到0.46.

请问有人做过相关的训练吗？loss2的最好结果能达到多少呢？test时的pearsonr可以达到多少呢？谢谢~

**Comment by dongtinghudeshui** [comment]
> 因为要在移动平台进行图像质量评价，所以利用mobileNet替换了VGG的网络结构。但是训练时发现loss2降到0.4左右就不在下降了，pearsonr的最好结果也只是达到0.46.
> 
> 请问有人做过相关的训练吗？loss2的最好结果能达到多少呢？test时的pearsonr可以达到多少呢？谢谢~
我也在做相关的工作有兴趣交流一下吗

**Comment by zengpeng175** [comment]
> 因为要在移动平台进行图像质量评价，所以利用mobileNet替换了VGG的网络结构。但是训练时发现loss2降到0.4左右就不在下降了，pearsonr的最好结果也只是达到0.46.
> 
> 请问有人做过相关的训练吗？loss2的最好结果能达到多少呢？test时的pearsonr可以达到多少呢？谢谢~


我也在做相关的工作，有兴趣交流一下吗？
