### ISSUE TITLE
No module named src.data_layer.rank_layer_live

### ISSUE THREAD

**Issue by shenguquanxin** [xialeiliu/RankIQA#39]
I0911 11:10:30.243358 515294 layer_factory.hpp:77] Creating layer data
ImportError: No module named src.data_layer.rank_layer_live
terminate called after throwing an instance of 'boost::python::error_already_set'
*** Aborted at 1568171430 (unix time) try "date -d @1568171430" if you are using GNU date ***
PC: @     0x7f0415c4f5f7 __GI_raise
*** SIGABRT (@0x7dcde) received by PID 515294 (TID 0x7f03f42777c0) from PID 515294; stack trace: ***
    @     0x7f0415c4f670 (unknown)
    @     0x7f0415c4f5f7 __GI_raise
    @     0x7f0415c50ce8 __GI_abort
    @     0x7f04177943df __gnu_cxx::__verbose_terminate_handler()
    @     0x7f0417792b16 __cxxabiv1::__terminate()
    @     0x7f0417792b4c std::terminate()
    @     0x7f0417792d72 __cxa_rethrow
    @     0x7f0416809d9a caffe::GetPythonLayer<>()
    @     0x7f041693f892 caffe::Net<>::Init()
    @     0x7f041694205e caffe::Net<>::Net()
    @     0x7f041694c76f caffe::Solver<>::InitTrainNet()
    @     0x7f041694cd25 caffe::Solver<>::Init()
    @     0x7f041694d01f caffe::Solver<>::Solver()
    @     0x7f041696b9a1 caffe::Creator_SGDSolver<>()
    @           0x40ba3f train()
    @           0x4080ce main
    @     0x7f0415c3bb15 __libc_start_main
    @           0x408a60 (unknown)
=============================
conda install caffe，请问是什么原因导致

**Comment by InspirationMy** [comment]
应该是python不知道去哪里照这个包
可以试试在python路径中添加一个到src的路径，这样python就知道该去哪里找这个文件了

**Comment by ayushrox** [comment]
same problem, anyone has a solution?
