### ISSUE TITLE
initialization.m: Index exceeds matrix dimensions

### ISSUE THREAD

**Issue by tobechao** [xialeiliu/RankIQA#4]
Hello, master, In the dataset preparation stage, run the initialization.m  in the gMADToolbox folder, I got a error: 

Finished image 982 / 982...
Non-linear mapping...
Generating test pairs...
Index exceeds matrix dimensions.

Error in generate_test_images (line 39)
            attacker_score=y_hat(img_idx);

Error in initialization (line 21)
    test_result = generate_test_images(algorithm_name, y_hat, WIVC_path);

The command is: initialization('psnr',0,1,'/data2/RankIQA/data/Waterloo','/data2/RankIQA/data/live2'), Can you tell me where is the fault? Thank you very much!

**Comment by xialeiliu** [comment]
Hello,
Sorry I don't know where is the error from. However, In our paper, we only need the function **distortion_generator.m** in support_functions folder to generate the ranked set for training.  
If you have any further issues about gMAD Toolbox, it's better to contact the authors who own the copyrights.

**Comment by tobechao** [comment]
En, thank you, I feel sorry to bother you. Only I follow the steps to run error, you mean:
cp ./support_functions/distortion_generator.m ../  and 
run initialization('distortion_generator',0,1,'/data2/RankIQA/data/Waterloo','/data2/RankIQA/data/live2')
I just want to get the data, [cry]?

**Comment by xialeiliu** [comment]
No problem.
I made a script to do so, which is in the **./RankIQA/data/data_generator/** folder. Hope it helps.

**Comment by tobechao** [comment]
Thank you very much, the matlab script generated some image data, I am ready to train the cnn. Thank you for your help!
