### ISSUE TITLE
评估人脸图片质量

### ISSUE THREAD

**Issue by phoenixzhua** [xialeiliu/RankIQA#44]
您好，我想请教一下，我想要对人脸检测得到的人脸图片序列进行评估，选出质量最好的3张，用这个方法可以吗？
我看训练数据的制作过程是在原图中加入各种噪声，对于一定时间段内（如30s）的视频序列，检测到的人脸图片，背景是类似的，所以得到的评分也是接近的？

**Comment by xialeiliu** [comment]
可以的，背景如果差不多的话理论上精度应该更高，可以集中判断人脸的部分。
