### ISSUE TITLE
version of pytorch program

### ISSUE THREAD

**Issue by upupbo** [xialeiliu/RankIQA#46]
When to provide a version of pytorch program

**Comment by mlkk518** [comment]
> When to provide a version of pytorch program

Hello,  I wonder if you have obtained  the pytorch program. Could you please give a glimpse to me ? Thanks a lot .

**Comment by upupbo** [comment]
> > When to provide a version of pytorch program
> 
> Hello, I wonder if you have obtained the pytorch program. Could you please give a glimpse to me ? Thanks a lot .

我没有，谢谢

**Comment by xialeiliu** [comment]
Sorry, we don't have the Pytorch version.

**Comment by mlkk518** [comment]
Thanks a lot for your reply.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xialei Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午4:45
收件人:&nbsp;"xialeiliu/RankIQA"<RankIQA@noreply.github.com&gt;;
抄送:&nbsp;"1198484350"<mlkkljh@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xialeiliu/RankIQA] version of pytorch program (#46)





 
Sorry, we don't have the Pytorch version.
