### ISSUE TITLE
RankIQA训练

### ISSUE THREAD

**Issue by pYq-lyz** [xialeiliu/RankIQA#47]
您好，我最近在复现RankIQA，利用rank数据集重新训练时，运行./src/RankIQA/live/train_vgg.sh时，并没有开始训练，而是直接结束了该命令，请问一下，如何重新训练RankIQA？谢谢！

**Comment by xialeiliu** [comment]
那你要检查一下你运行的是否正确。

**Comment by Yl0o** [comment]
@pYq-lyz 你好，你说的没有开始训练直接结束，是什么意思？是直接执行完就不动了吗？
