### ISSUE TITLE
the requests of  code  announce 17 type plus noise method

### ISSUE THREAD

**Issue by zengjichen** [xialeiliu/RankIQA#5]
Excuse me,Is it convenient to announce 17 type plus noise method? thank you very much!

**Comment by xialeiliu** [comment]
Thanks for your interest. 
Basically, we just followed the TID2013 dataset generating process to generate the possible distortion types. For further information, you could ask the authors who have the license and rights of TID2013 dataset. I will let you know when our code is ready.
