### ISSUE TITLE
关于训练合成数据

### ISSUE THREAD

**Issue by ppl21847** [xialeiliu/RankIQA#56]
请教一下，合成的rank数据，在训练的时候不同的模糊方法获取的不同级别的图像，怎么保证level是一样的？

**Comment by ppl21847** [comment]
在RankIQA的情况下 不同类型的失真的合成图像可以放同一个batch里面训练吗？

**Comment by xialeiliu** [comment]
不同类型的失真是没有一起比较训练的。

**Comment by ppl21847** [comment]
> 不同类型的失真是没有一起比较训练的。

好的 谢谢
麻烦再请假一下，可不可以用在线方法生成不同level图片，level的参数是如何给定的。

**Comment by xialeiliu** [comment]
理论上是可以的，具体参数和离线生成是一样的，可以参考：
https://github.com/xialeiliu/RankIQA/tree/master/data/rank_tid2013

**Comment by ppl21847** [comment]
> 理论上是可以的，具体参数和离线生成是一样的，可以参考：
> https://github.com/xialeiliu/RankIQA/tree/master/data/rank_tid2013

好的，谢谢

**Comment by ppl21847** [comment]
您好，麻烦再请教一下 你同一个batch里取的是同一个图片同一种类型的图片吗？
