### ISSUE TITLE
Move pre-trained models from baidu

### ISSUE THREAD

**Issue by ArthurSav** [xialeiliu/RankIQA#8]
The pre-trained models are stored in [baidu](https://pan.baidu.com/s/1jIabZKU#list/path=%2FRankIQA_models)

1. They don't allow to download the files without installing their software and registering an account.
2. Registering an account requires a Chinese phone number

May i suggest moving the models to [archive.org](https://archive.org/upload/) ?

**Comment by xialeiliu** [comment]
I have uploaded the same files to Google drive, here is the link https://drive.google.com/drive/folders/1S55n7tHBfJop3Z-nDjHXvEc34HmHowZt: 
Thanks for your suggestion.
